### ISSUE TITLE
Enable remote Killswitch

### ISSUE THREAD

**Issue by knjensen** [JavaDogs/cws#30]
The current Kill Switch is system salt. If changed, all existing accounts will be unrecoverable, and thus all data as well. However, the current implementation explicitly disallows updating this via the API. And thus, it is not possible to easily disable the system!

A suggestion is to remove the limiting of changing settings, and instead add a piece of code, which will allow the System Administrator to update the Salt as a special case, whereby the keys for the Administrator is re-encrypted using the new Salt. This has the benefit, that the Administrator can use the standard API to control everything, including the Salt - without having to manually update the Database. Further, for sensitive setups, it will also allow a quick killing of the system.

**Comment by knjensen** [comment]
The feature can be implemented relatively easily, and as part of the implementation, a simplification of the underlying data model can also be made whereby the modifiable flag is removed. The only value where the feature is used, is for the system salt.

**Comment by pilz** [comment]
A system wide kill switch is possible by accessing the database and changing the system salt. Any administrator can do this. Also an administrator could turn the system easily off by shutting the database down or deactivating the connection to the database. Exposing the killswitch to a wider audience could be more damaging due to misuse than to actually provide more benefit.

Instead a personal killswitch could be very interesting, because personal passwords are quite likely to become compromised. In that situation a user could deactivate his account easily - e.g. a button in the user profile - and only his access would be destroyed.

**Comment by knjensen** [comment]
Turning question into task:

- Add new Action to the processMember request called "invalidate"
- Add Logic to the ProcessMemberService, which will ensure that the account is invalidated to the point of not being reparable.
- Add testing of this, to ensure that the account is completely useless

**Comment by knjensen** [comment]
With the latest commit, this feature should be enabled. Closing ticket now.
